### ISSUE TITLE
Wrong capitalization in vagrant-host.rb?

### ISSUE THREAD

**Issue by Penaz91** [soapy1/vagrant-host-plugin-skeleton-ruby#1]
Greetings!

I've been using this skeleton as a base for supporting Artix Linux via plugin, and I noticed a mistake that stumped me for a couple minutes:

https://github.com/soapy1/vagrant-host-plugin-skeleton-ruby/blob/main/lib/vagrant-host.rb#L25

According to the Vagrant documentation (https://developer.hashicorp.com/vagrant/docs/plugins/hosts#definition-component) `host` should be `Host`.

This made the plugin crash with a "too few parameters" error. After changing the capitalization as stated above, everything seems to be working.

Thank you for your attention!

**Comment by soapy1** [comment]
Thanks for catching that!
